# Generated by Django 4.0.6 on 2022-09-12 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailaccount',
            name='address',
        ),
        migrations.RemoveField(
            model_name='emailaccount',
            name='phone_number',
        ),
    ]
