# Generated by Django 4.0.6 on 2022-09-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_care', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='Working_hours',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='clinic_opening_hours',
        ),
        migrations.AddField(
            model_name='doctor',
            name='friday',
            field=models.CharField(blank=True, default='Friday', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='monday',
            field=models.CharField(blank=True, default='Monday', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='saturday',
            field=models.CharField(blank=True, default='Saturday', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='sunday',
            field=models.CharField(blank=True, default='Sunday', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='thursday',
            field=models.CharField(blank=True, default='Thursday', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='tuesday',
            field=models.CharField(blank=True, default='Tuesday', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='wednesday',
            field=models.CharField(blank=True, default='Wednesday', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='ClinicOpeningHours',
        ),
    ]
