# Generated by Django 4.1.1 on 2022-09-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_care', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='order', to='baby_care.item', verbose_name='items'),
        ),
    ]
