# Generated by Django 4.1.1 on 2022-09-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_care', '0002_remove_doctor_working_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_sub_category',
        ),
        migrations.AddField(
            model_name='product',
            name='ClotheSubCategoryChoices',
            field=models.CharField(blank=True, choices=[('Bijama', 'BIJAMA'), ('T_Shirt', 'T_SHIRT'), ('Underwaer', 'Underwaer'), ('None', 'NONE')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ContainerSubCategoryChoices',
            field=models.CharField(blank=True, choices=[('Fixed', 'FIXED'), ('Movable', 'MOVABLE'), ('None', 'NONE')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='FoodSubCategoryChoices',
            field=models.CharField(blank=True, choices=[('Milk', 'MILK'), ('Instant_Cereal', 'INSTANT_CEREAL'), ('None', 'NONE')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='FoodToolSubCategoryChoices',
            field=models.CharField(blank=True, choices=[('Cup', 'CUP'), ('Baby_Bottle', 'BABY_BOTTLE'), ('None', 'NONE')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='FurnitureSubCategoryChoices',
            field=models.CharField(blank=True, choices=[('Cover', 'COVER'), ('Pillow', 'PILLOW'), ('Mattress', 'MATTRESS'), ('None', 'NONE')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ShowerToolSubCategoryChoices',
            field=models.CharField(blank=True, choices=[('Soap', 'SOAP'), ('Towel', 'TOWEL'), ('Loofah', 'LOOFAH'), ('Shampoo', 'SHAMPOO'), ('None', 'NONE')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='VehicleSubCategoryChoices',
            field=models.CharField(blank=True, choices=[('Jogger', 'JOGGER'), ('Stroller', 'STROLLER'), ('None', 'NONE')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='friday',
            field=models.CharField(blank=True, default='Friday ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='monday',
            field=models.CharField(blank=True, default='Monday ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='saturday',
            field=models.CharField(blank=True, default='Saturday ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='sunday',
            field=models.CharField(blank=True, default='Sunday ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='thursday',
            field=models.CharField(blank=True, default='Thursday ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='tuesday',
            field=models.CharField(blank=True, default='Tuesday ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='wednesday',
            field=models.CharField(blank=True, default='Wednesday ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='age',
            field=models.CharField(blank=True, choices=[('One_To_Six_Months', 'ONE_TO_SIX_MONTHS'), ('More_Than_Six_Months', 'MORE_THAN_SIX_MONTHS'), ('None', 'NONE')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'MALE'), ('Female', 'FEMALE'), ('None', 'NONE')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('Small', 'SMALL'), ('Medium', 'MEDIUM'), ('Large', 'LARGE'), ('None', 'NONE')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stars',
            field=models.IntegerField(),
        ),
    ]
