# Generated by Django 4.0.6 on 2022-09-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_care', '0002_remove_doctor_working_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=10)),
                ('home_address', models.CharField(max_length=50)),
                ('work_address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_sub_category',
        ),
        migrations.AddField(
            model_name='product',
            name='clothe_sub_category',
            field=models.CharField(blank=True, choices=[('Bijama', 'BIJAMA'), ('T_Shirt', 'T_SHIRT'), ('Underwaer', 'Underwaer')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='container_sub_category',
            field=models.CharField(blank=True, choices=[('Fixed', 'FIXED'), ('Movable', 'MOVABLE')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='food_sub_category',
            field=models.CharField(blank=True, choices=[('Milk', 'MILK'), ('Instant_Cereal', 'INSTANT_CEREAL')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='food_tool_sub_category',
            field=models.CharField(blank=True, choices=[('Cup', 'CUP'), ('Baby_Bottle', 'BABY_BOTTLE')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='furniture_sub_category',
            field=models.CharField(blank=True, choices=[('Cover', 'COVER'), ('Pillow', 'PILLOW'), ('Mattress', 'MATTRESS')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shower_tool_sub_category',
            field=models.CharField(blank=True, choices=[('Soap', 'SOAP'), ('Towel', 'TOWEL'), ('Loofah', 'LOOFAH'), ('Shampoo', 'SHAMPOO')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='vehicle_sub_category',
            field=models.CharField(blank=True, choices=[('Jogger', 'JOGGER'), ('Stroller', 'STROLLER')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='friday',
            field=models.CharField(blank=True, default='Friday ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='monday',
            field=models.CharField(blank=True, default='Monday ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='saturday',
            field=models.CharField(blank=True, default='Saturday ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='sunday',
            field=models.CharField(blank=True, default='Sunday ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='thursday',
            field=models.CharField(blank=True, default='Thursday ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='tuesday',
            field=models.CharField(blank=True, default='Tuesday ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='wednesday',
            field=models.CharField(blank=True, default='Wednesday ', max_length=20, null=True),
        ),
    ]
