# Generated by Django 4.1.1 on 2022-09-29 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baby_care', '0002_alter_order_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='age',
            field=models.CharField(blank=True, choices=[('One_To_Six_Months', 'ONE_TO_SIX_MONTHS'), ('More_Than_Six_Months', 'MORE_THAN_SIX_MONTHS'), ('None', 'None')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='clothe_sub_category',
            field=models.CharField(blank=True, choices=[('Bijama', 'BIJAMA'), ('T_Shirt', 'T_SHIRT'), ('Underwaer', 'Underwaer'), ('None', 'None')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='container_sub_category',
            field=models.CharField(blank=True, choices=[('Fixed', 'FIXED'), ('Movable', 'MOVABLE'), ('None', 'None')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='food_sub_category',
            field=models.CharField(blank=True, choices=[('Milk', 'MILK'), ('Instant_Cereal', 'INSTANT_CEREAL'), ('None', 'None')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='food_tool_sub_category',
            field=models.CharField(blank=True, choices=[('Cup', 'CUP'), ('Baby_Bottle', 'BABY_BOTTLE'), ('None', 'None')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='furniture_sub_category',
            field=models.CharField(blank=True, choices=[('Cover', 'COVER'), ('Pillow', 'PILLOW'), ('Mattress', 'MATTRESS'), ('None', 'None')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'MALE'), ('Female', 'FEMALE'), ('None', 'None')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='shower_tool_sub_category',
            field=models.CharField(blank=True, choices=[('Soap', 'SOAP'), ('Towel', 'TOWEL'), ('Loofah', 'LOOFAH'), ('Shampoo', 'SHAMPOO'), ('None', 'None')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('Small', 'SMALL'), ('Medium', 'MEDIUM'), ('Large', 'LARGE'), ('None', 'None')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='vehicle_sub_category',
            field=models.CharField(blank=True, choices=[('Jogger', 'JOGGER'), ('Stroller', 'STROLLER'), ('None', 'None')], max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AddField(
            model_name='card',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baby_care.product'),
        ),
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
