# Generated by Django 4.1.1 on 2022-09-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_care', '0003_card_alter_product_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='item_qty',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='item_qty'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_qty',
            field=models.IntegerField(default=1, verbose_name='item_qty'),
        ),
    ]
